spring.application.name=helloWorldApp
spring.datasource.url=postgresql://postgres:IYSlVtDiOvIeRpZeFjcLRiQIhqZjtIhq@postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=112233postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
